name: Screenshot Site
on:
  push:
    branches:
      - screen-wip

jobs:
  screenshot:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    # we need to set --config based on the repository, i.e., the 
    # test repository needs to additionally include the _config-test.yml
    # which sets the baseurl appropriately
    # the cleanest way I can find to do this is to conditionally set an
    # env var which is used in the publish task below
    - name: set vars
      run: |
        if [[ "$GITHUB_REPOSITORY" == */blog-test ]]; then
          echo "Using testing config"
          echo "EXTRA_BUILD_ARGS=--config _config.yml,_config-test.yml" >> $GITHUB_ENV
        fi

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Publish to GitHub
      uses:  helaili/jekyll-action@64b759fc0e18682ff47a0522072df02762a76af2
      with:
        target_branch: gh-pages
        target_path: ../workspace/_site
        build_only: true
        jekyll_build_options: ${{ env.EXTRA_BUILD_ARGS }}

    - name: Take and publish screenshots
      run: _scripts/snapshot.sh
      env:
        SNAPSHOT_REPO: https://github.com/travisdowns/blog-screenshots
        SNAPSHOT_BRANCH: master
        SNAPSHOT_USER: ${{ github.actor }}
        SNAPSHOT_EMAIL: ${{ github.actor }}@users.noreply.github.com
        SNAPSHOT_REPO_AUTH: ${{ secrets.SNAPSHOT_REPO_AUTH }}
    